[package]
name = "iepm-resolver"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
iepm-core = { path = "../iepm-core" }
semver.workspace = true
thiserror.workspace = true

[dev-dependencies]
iepm-registry = { path = "../iepm-registry" }
serde_yaml.workspace = true
